# Henrick Oliveira de Souza     12121BSI237

# Notícias recentes sobre a guerra no Irã

In [ ]:
# Trecho de código apenas para coleta de dados de uma API de Notícias

# Um possivel problema pra ser corrigido e observado é que se essa parte de codigo é executada, a de embedding e a de chunk
# precisa necessariamente também ser executada se não o código do RAG quebra, porque alguns campos são considerados só em
# tempo de execução e não sao salvos no JSON, como os embeddings por ex

import re
import requests
import pandas as pd
import unicodedata
import os
import nltk
from nltk.tokenize import sent_tokenize
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

nltk.download("punkt")

def clean_text(text):
    #Isso serve só pra dar uma leve contida nos ruídos que essas informações poderiam causar na hora de gerar embedding
    patterns = [
        r"O Portal de Notícias.*",
        r"Veja as principais notícias.*",
        r"Últimas notícias.*",
        r"Notícias e informações.*"
    ]

    for p in patterns:
        text = re.sub(p, "", text)

    return text.strip()



def normalize_text(text):
    if text is None:
        return None
    
    text = unicodedata.normalize("NFD", text)
    text = "".join(c for c in text if unicodedata.category(c) != "Mn")
    
    text = text.lower()
    
    return text

#Coloquei tudo hard-coded mesmo porque a automação pra esse processo estava um pouco chata, então para buscar
# notícias novas e expandir a base é so trocar a página, ou esperar alguns dias passarem pra buscar novas#
page = 9
api_key= "4cb501f44b919b47ee7334acdc742dfb"
file_path = "dataset_noticias.json"
url = f"https://gnews.io/api/v4/search?q=guerra+Irã&lang=pt&country=br&max=100&apikey=4cb501f44b919b47ee7334acdc742dfb&page={page}"

new_articles = []

if os.path.exists(file_path):
    df_existing = pd.read_json(file_path)
else:
    df_existing = pd.DataFrame()

existing_urls = set()

if not df_existing.empty and "url" in df_existing.columns:
    existing_urls = set(df_existing["url"])

for page in range(1,10):

    response = requests.get(url).json()

    if response.get("status") != "ok":
        print("Erro da API:", response)
        break
    print(response)
for article in response.get("articles", []):
    
    new_articles.append({
        "title": article.get("title"),
        "description": article.get("description"),
        "content": article.get("content"),
        "url": article.get("url"),
        "publishedAt": article.get("publishedAt"),
        "source": article.get("source", {}).get("name")

    })
df_new = pd.DataFrame(new_articles)

df_final = pd.concat([df_existing, df_new],ignore_index=True)
df_final = df_final.drop_duplicates(subset="title") #Retira as notícias iguais
df_final = df_final.dropna(subset=["title","description"])
df_final["text"] = df_final["title"] + " " + df_final["description"] #Aparentemente condensar o título com a descrição fica melhor pra ML
df_final["text"] = df_final["text"].apply(clean_text)
df_final.to_json("dataset_noticias.json", orient="records", indent=4)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Erro da API: {'information': {'realTimeArticles': {'message': 'Real-time news data is only available on paid plans. Free plan has a 12-hour delay. Upgrade your plan here to remove the delay: https://gnews.io/change-plan'}}, 'totalArticles': 2751, 'articles': [{'id': '9e930d717bb3e64d98683bced8b028ad', 'title': 'Trump não deve conseguir mudar o regime no Irã só com bombardeios, diz especialista', 'description': 'Para Ronaldo Carmona, professor de Geopolítica da Escola Superior de Guerra, conflito no Irã e ação americana na Venezuela mostram que países como o Brasil ainda precisam se preocupar com dissuasão contra forças bélicas externas.', 'content': 'Uma semana após os primeiros bombardeios dos Estados Unidos contra o Irã, o conflito no Golfo entrou em uma fase marcada pela incerteza e pela escalada de tensões.\nMesmo com a morte de seu líder supremo, o aiatolá Ali Khamenei - morto na primeira ond... [8960 chars]', 'url': 'https://www.correiobraziliense.com.br/mundo/2026/03/7370773-trump-nao-deve-conseguir-mudar-o-regime-no-ira-so-com-bombardeios-diz-especialista.html', 'image': 'https://midias.correiobraziliense.com.br/_midias/jpg/2026/03/08/dbe13700-1b11-11f1-870b-03d961994130-65049806.jpg?20260308142508?20260308142508', 'publishedAt': '2026-03-08T14:24:57Z', 'lang': 'pt', 'source': {'id': 'b41b1b225b446c4cbf527bd4d80b25ae', 'name': 'Correio Braziliense', 'url': 'https://www.correiobraziliense.com.br', 'country': 'br'}}, {'id': '66ed282767d62e205a3d17e5ce2caf8a', 'title': 'Os contornos econômicos da guerra: EUA e Israel bombardeiam 4 depósitos de petróleo no Irã', 'description': 'Diante da Guerra, os preços do petróleo disparam 28% em apenas uma semana', 'content': 'Quatro depósitos de petróleo e um centro logístico de derivados de petróleo, localizados em Teerã e suas imediações, foram bombardeados na noite de sábado, 7, pelos Estados Unidos e por Israel, informou Keramat Veyskaram, presidente da empresa nacion... [1385 chars]', 'url': 'https://veja.abril.com.br/mundo/eua-e-israel-entram-na-guerra-economica-e-bombardeiam-4-depositos-de-petroleo-no-ira/', 'image': 'https://veja.abril.com.br/wp-content/uploads/2024/10/000_36J3372.jpg?quality=70&strip=info&resize=1080,565&crop=1', 'publishedAt': '2026-03-08T13:40:06Z', 'lang': 'pt', 'source': {'id': '6a029bcd17d11a505b0aed88fccfa943', 'name': 'Veja', 'url': 'https://veja.abril.com.br', 'country': 'br'}}, {'id': '916bd92ddc72d06e6816b11deb5be3e6', 'title': 'Força aérea do Irã conta com jatos produzidos na década de 1960', 'description': 'A supremacia da guerra nos ares de Estados Unidos e Israel escancarou a obsolescência da força aérea do Irã', 'content': 'A supremacia da guerra nos ares de Estados Unidos e Israel escancarou a obsolescência da força aérea do Irã, cuja frota dispõe de aviões e helicópteros que estariam mais aptos às salas de museu do que ao cenário da guerra no Oriente Médio.\nA grande m... [1797 chars]', 'url': 'https://www.gazetadopovo.com.br/mundo/forca-aerea-do-ira-conta-com-jatos-produzidos-na-decada-de-1960/', 'image': 'https://media.gazetadopovo.com.br/2026/03/08093550/8022174342001w.jpg', 'publishedAt': '2026-03-08T13:10:57Z', 'lang': 'pt', 'source': {'id': '9c1d73ba77989b4de01336d5b29f7e4e', 'name': 'Gazeta do Povo', 'url': 'https://www.gazetadopovo.com.br', 'country': 'br'}}, {'id': '73268d92c958bd4bf66c5f5cf54f5d3c', 'title': 'Como artistas do Irã foram linha de frente da luta contra o regime de Ali Khamenei', 'description': 'Em meio à névoa da guerra, alguns dos cineastas iranianos mais renomados foram recentemente a público para comemorar o assassinato do aiatolá Ali', 'content': 'Em meio à névoa da guerra, alguns dos cineastas iranianos mais renomados foram recentemente a público para comemorar o assassinato do aiatolá Ali Khamenei. O líder supremo, contra quem muitos deles se opunham, foi morto por bombardeios de Israel e do... [5350 chars]', 'url': 'https://www.bemparana.com.br/cultura/como-artistas-do-ira-foram-linha-de-frente-da-luta-contra-o-regime-de-ali-khamenei/', 'image': 'https://www.bemparana.com.br/wp-content/uploads/2026/03/a-semente-do-fruto-sagrado.jpg?v=08.03.14.51.21', 'publishedAt': '2026-03-08T13:05:00Z', 'lang': 'pt', 'source': {'id': '8cb1655d380159241721bc21ecb5c93d', 'name': 'Jornal Do Estado', 'url': 'https://www.bemparana.com.br', 'country': 'br'}}, {'id': '344753c49cc892fa09bb6daf4a267921', 'title': 'Número de civis mortos no Irã na guerra sobe para 1.200, diz organização', 'description': 'Total, que inclui 194 crianças, é referente às 18h de sábado (7), informou a HRANA', 'content': 'Pelo menos 1.205 civis foram mortos no Irã desde que os EUA e Israel começaram a atacar o país no último sábado (28), segundo a HRANA, Agência de Notícias de Ativistas de Direitos Humanos, com sede nos EUA.\nO total, que inclui 194 crianças, é referen... [755 chars]', 'url': 'https://www.cnnbrasil.com.br/internacional/numero-de-civis-mortos-no-ira-na-guerra-sobe-para-1-200-diz-organizacao/', 'image': 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2026/02/ap26059256811672-e1772487765983.avif?w=1200&h=630&crop=1', 'publishedAt': '2026-03-08T12:41:08Z', 'lang': 'pt', 'source': {'id': 'd88e1971d59f95d0ea654840aaaaba48', 'name': 'CNN Brasil', 'url': 'https://www.cnnbrasil.com.br', 'country': 'br'}}, {'id': '9a072416cfff10de548440208e8c7ae0', 'title': 'Guerra de Trump no Irã eleva preço da gasolina nos EUA e Casa Branca alega "ganho de longo prazo"', 'description': 'Porta-voz da Casa Branca afirma que alta nos combustíveis causada pelo conflito com o Irã seria uma “disrupção temporária” no mercado de energia', 'content': '247 - A escalada da guerra envolvendo o Irã já começa a provocar efeitos diretos no mercado de energia dos Estados Unidos, com aumento nos preços da gasolina. A secretária de imprensa da Casa Branca, Karoline Leavitt, afirmou que a elevação dos combu... [1530 chars]', 'url': 'https://www.brasil247.com/economia/guerra-de-trump-no-ira-eleva-preco-da-gasolina-nos-eua-e-casa-branca-alega-ganho-de-longo-prazo', 'image': 'https://cdn.brasil247.com/pb-b247gcp/swp/jtjeq9/media/20260107150140_e37e7deffd6e0a958960c2c4aa609b6edf6c350735c70dfd709b75e9e1dbe979.jpg', 'publishedAt': '2026-03-08T12:23:47Z', 'lang': 'pt', 'source': {'id': '5e8b3dbf4a0e8465cc2b21565bb4953e', 'name': 'Brasil 247', 'url': 'https://www.brasil247.com', 'country': 'br'}}, {'id': '02566fab3c634972234a9f9e5dbb08fe', 'title': 'Segurança alimentar do Golfo está em xeque em meio à guerra do Irã', 'description': 'Estados do Golfo enfrentam seu maior desafio desde a crise global de 2008, à medida que o conflito com o Irã ameaça o serviço de portos e interrompe a navegação pelo Estreito de Ormuz', 'content': 'Os ricos estados do Golfo estão enfrentando seu maior desafio de segurança alimentar desde a crise global de 2008, à medida que o conflito com o Irã ameaça o serviço de portos e interrompe a navegação pelo Estreito de Ormuz. Durante a turbulência fin... [319 chars]', 'url': 'https://valor.globo.com/mundo/noticia/2026/03/08/segurana-alimentar-do-golfo-est-em-xeque-em-meio-guerra-do-ir.ghtml', 'image': 'https://s2-valor.glbimg.com/BvPAIowxUklHCKTBk8SPeHEmFXk=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_63b422c2caee4269b8b34177e8876b93/internal_photos/bs/2026/J/m/CBCHncRBKKlAVBlr5z2g/2026-03-04t133559z-1536827899-rc20xjav4euz-rtrmadp-3-iran-crisis-energy.jpg', 'publishedAt': '2026-03-08T12:20:37Z', 'lang': 'pt', 'source': {'id': '40c7b6fe9f2a22f69242917482cdbf0a', 'name': 'Valor Econômico', 'url': 'https://valor.globo.com', 'country': 'br'}}, {'id': 'd400b299b4a6c5ee492a075cf4c90f92', 'title': 'Combustíveis disparam com guerra no Irã e ameaça ao Estreito de Ormuz', 'description': 'Conflito iniciado por EUA e Israel pressiona oferta global de petróleo e eleva preços de gasolina, diesel e querosene de aviação', 'content': '247 - A escalada da guerra envolvendo Estados Unidos, Israel e Irã provocou forte impacto nos mercados globais de energia e já se reflete no preço dos combustíveis. A interrupção do fluxo de petróleo pelo Estreito de Ormuz — uma das rotas marítimas m... [5752 chars]', 'url': 'https://www.brasil247.com/economia/combustiveis-disparam-com-guerra-no-ira-e-ameaca-ao-estreito-de-ormuz', 'image': 'https://cdn.brasil247.com/pb-b247gcp/swp/jtjeq9/media/20260303100316_73520a747cc39dda49eaa90f18f8c0a514b3ad2d2ee0d33b33092d8206f4b4c2.jpg', 'publishedAt': '2026-03-08T12:06:17Z', 'lang': 'pt', 'source': {'id': '5e8b3dbf4a0e8465cc2b21565bb4953e', 'name': 'Brasil 247', 'url': 'https://www.brasil247.com', 'country': 'br'}}, {'id': '45530d633b0df068267cbf5f8f032622', 'title': 'Israel ataca depósitos de petróleo no Irã em nova fase da guerra', 'description': 'EUA também intensificaram bombardeios; explosões são registradas em Teerã e em outras partes do território iraniano. Leia no Poder360.', 'content': 'As forças armadas dos Estados Unidos e de Israel intensificaram seus bombardeios contra o Irã na noite de sábado (7.mar.2026), incluindo ataques a depósitos de petróleo perto de Teerã, capital do país persa. A guerra entrou na 2ª semana.\nO primeiro-m... [4253 chars]', 'url': 'https://www.poder360.com.br/poder-internacional/israel-ataca-depositos-de-petroleo-no-ira-em-nova-fase-da-guerra/', 'image': 'https://static.poder360.com.br/2026/03/Incendio-deposito-combustivel-Teera-Ira-8-mar-2026-848x477.jpg', 'publishedAt': '2026-03-08T12:04:36Z', 'lang': 'pt', 'source': {'id': '0bcdd5af79e21aa5f0686a8619580232', 'name': 'Poder360', 'url': 'https://www.poder360.com.br', 'country': 'br'}}, {'id': 'e3c6706ae2aca9bcf17f797b1bd722d6', 'title': 'Itália não entrará na guerra do Irã, afirma Meloni', 'description': 'A premiê da Itália, Giorgia Meloni, afirmou que o país não faz parte da guerra contra o Irã e que trabalha para reduzir a tensão na região', 'content': 'A primeira-ministra da Itália, Giorgia Meloni, afirmou que o país não faz parte da guerra contra o Irã, "nem tem intenção de ser", e que está trabalhando para reduzir a tensão e avaliar se existe a possibilidade de retomar as negociações.\n"O governo ... [1588 chars]', 'url': 'https://www.gazetadopovo.com.br/mundo/italia-nao-entrara-na-guerra-do-ira-afirma-meloni/', 'image': 'https://media.gazetadopovo.com.br/2026/03/08084146/8023325816001w.jpg', 'publishedAt': '2026-03-08T11:42:33Z', 'lang': 'pt', 'source': {'id': '9c1d73ba77989b4de01336d5b29f7e4e', 'name': 'Gazeta do Povo', 'url': 'https://www.gazetadopovo.com.br', 'country': 'br'}}]}

In [82]:
# Parte dos chunkings 

# Não tinha muita ideia do tamanho ideal, pesquisei um pouco e parece que esse é um tamanho OK
def chunk_text(text, max_words=80, overlap=20):
    
    sentences = sent_tokenize(text, language="portuguese")
    
    chunks = []
    current_chunk = []
    word_count = 0
    
    for sentence in sentences:
        words = sentence.split()
        
        if word_count + len(words) > max_words:
            chunks.append(" ".join(current_chunk))
            
            overlap_words = current_chunk[-overlap:]
            current_chunk = overlap_words + words
            word_count = len(current_chunk)
        else:
            current_chunk += words
            word_count += len(words)
    
    if current_chunk:
        chunks.append(" ".join(current_chunk))
        
    return chunks

chunked_texts_list = []

for documents in df_final["text"]:
   chunked_text = chunk_text(documents) 
   chunked_texts_list.append(chunked_text)
print (chunked_texts_list)

[['Irã afirma ter atingido petroleiro americano no Golfo, sem confirmação imediata A Guarda Revolucionária afirmou, em comunicado divulgado na quinta-feira pela mídia estatal, que, em tempos de guerra, a passagem pelo Estreito de Ormuz ficará sob o controle da República Islâmica'], ['Países do Golfo estão preocupados com risco de guerra civil no Irã, diz UE O temor é que uma crise se instale durante a escolha da próxima liderança do regime, após a morte do aiatolá Ali Khamenei no sábado'], ['Guerra de Trump no Irã leva gasolina a seu maior preço em 11 meses nos EUA Alta recente está ligada à guerra envolvendo o Irã e à restrição no Estreito de Ormuz, rota estratégica por onde passa cerca de 20% do petróleo mundial'], ['Sri Lanka tenta salvar vidas em outro navio do Irã Torpedo americano afundou embarcação de guerra iraniana no oceano Índico; há dezenas de feridos e desaparecidos'], ['Pesquisa eleitoral, dados de emprego e avanço da guerra entre EUA e Irã marcam o dia Cesta Básica: tudo que você precisa saber para começar o dia bem informado'], ['França autorizou EUA a usarem bases francesas na guerra, diz emissora País tem criticado ataque dos Estados Unidos e de Israel ao Irã, mas reposicionou meios militares ao enviar seu porta-aviões nuclear para o Mediterrâneo'], ['Irã diz ter atingido petroleiro dos EUA, em nova escalada da guerra Caso o ataque seja confirmado, será o primeiro incidente conhecido envolvendo diretamente uma embarcação americana no Golfo desde o início da guerra'], ['Curdos dizem estar prontos para se juntar à guerra Grupos dissidentes curdos iranianos, que vivem no norte do Iraque, estão se preparando para uma possível operação militar no Irã. Os EUA pediram aos curdos iraquianos que os apoiem, segundo autoridades curdas ouvidas pela agência Associated Press.Os grupo'], ['Bolsas da Europa estendem recuperação, com foco em desdobramentos da guerra Conflito travado por Estados Unidos e Israel contra o Irã chega ao sexto dia sem perspectiva de solução rápida'], ['Irã lança novos ataques contra Israel e bases dos EUA no sexto dia da guerra O Irã lançou nesta quinta-feira (5) uma nova onda de ataques contra Israel e bases militares dos Estados Unidos, no sexto dia da guerra no Oriente Médio. Israel, por sua vez, anunciou uma ofensiva de "larga escala" contra Teerã e a continuidade dos bombar'], ['Irã afirma que atacou petroleiro dos EUA no Golfo Pérsico Guerra entrou no sexto dia'], ['Guerra contra o Irã entra no sexto dia com expansão do conflito no Oriente Médio Ataques dos EUA e de Israel ampliam tensão regional, elevam número de vítimas e provocam impactos no Golfo, no Líbano e no Iraque'], ['Prisão de Vorcaro detona novas revelações. Guerra no Irã amplia efeitos Polícia Federal revela suspeita de ameaças e lavagem de dinheiro. Conflito se estende além do Oriente Médio. Leia na Gazeta do Povo'], ['Guerra no Oriente Médio se intensifica com ataques do Irã aos curdos no Iraque Novas explosões abalaram Teerã nesta quinta-feira, 5, enquanto o Irã anunciou que atacou grupos curdos no Iraque, o que provoca o temor de uma ampliação da'], ['Futuros de NY recuam após recuperação de Wall Street, com guerra no Irã em foco Investidores acompanham desdobramentos do conflito no Irã após recuperação das bolsas de Nova York na sessão anterior'], ['Nenhum lado está disposto a recuar e risco de guerra civil é real, diz Ali Vaez, especialista em Irã Em entrevista ao Estadão, Ali Vaez fala sobre o futuro da República Islâmica, a sucessão de Ali Khamenei e a estratégia iraniana para confrontar os EUA'], ['Guerra no Oriente Médio não deve afetar exportações de milho Irã responde por cerca de 20% das vendas brasileiras do grão, que ocorrem em maior volume a partir do mês de maio'], ['Hezbollah e Irã disparam contra Israel de forma simultânea pela primeira vez durante a guerra Sirenes foram ativadas em todo o território israelense durante a madrugada desta quinta-feira, 5, e moradores relataram várias explosões'], ['Hezbollah e Irã disparam contra Israel de forma simultânea pela 1ª vez na guerra'], ['Espanha enviará fragata ao Chipre em meio a tensão com EUA por guerra no Irã'], ['Voos parcialmente retomados e explosões em Tel Aviv, Jerusalém, Beirute e Teerã; o que aconteceu até agora no 6º dia da guerra Guerra no Oriente Médio entra em seu sexto dia nesta quinta-feira (5/3) com notícias de novos ataques de Israel e Irã.'], ['Guerra no Irã: bloqueio do Estreito de Ormuz pode afetar exportações brasileiras Frango, madeira e papel estão entre os itens que cruzam a rota. No ano passado, 158.300 contêineres saíram do país rumo ao Golfo Pérsico'], ['Sexto dia de guerra tem ataques de Israel, do Irã e envio de navios europeus para a região Sexto dia de guerra tem ataques de Israel, do Irã e envio de navios europeus para a região -'], ["Irã diz que 'EUA vão se arrepender amargamente' por afundar navio militar perto do Sri Lanka Secretário de Guerra de Trump, Pete Hegseth, afirmou que um submarino norte-americano derrubou o navio iraniano com o lançamento de um torpedo. Caso ocorreu perto da costa do Sri Lanka, e governo do país disse que ainda busca mais de cem desaparecidos."], ['Número de mortos passa de 1.160 na guerra no Oriente Médio; saiba o total Dezenas de pessoas foram mortas no Oriente Médio desde que os Estados Unidos e Israel atacaram o Irã em 28 de fevereiro'], ['Inacreditável: no conforto do Ocidente, estudantes louvam aiatolá morto A guerra no Irã provoca intensos debates sobre legalidade, inclusive entre aliados dos Estados Unidos, mas é insano glorificar Khamenei'], ['Veja quais são as últimas informações sobre a guerra no Oriente Médio Manchetes envolvem ataque dos EUA a um navio do Irã, que já acumula mais de 1.100 mortos desde o início do conflito'], ['Guerra no Irã se soma à crise da Raízen e dificulta captações externas Estrangeiros estão reticentes em adquirir títulos de dívida de companhias brasileiras'], ['Guarda Revolucionária do Irã se prepara para \'seis meses de guerra\'; Líbano alerta para crise humanitária Neste domingo (8), no nono dia de conflito, a Guarda Revolucionária do Irã afirmou estar preparada para enfrentar "pelo menos seis meses de guerra intensa" contra os Estados Unidos e Israel. O grupo declara já ter atacado mais de 200 alvos americanos e israelenses na região desde o início das hostilidades.', 'O grupo declara já ter atacado mais de 200 alvos americanos e israelenses na região desde o início das hostilidades. Líbano adverte para uma "catástrofe humanitária" caso o conflito no Oriente Médio não seja interrompido.'], ["Guarda Revolucionária do Irã afirma estar preparada para 'seis meses de guerra intensa'"], ['Irã aprendeu com erro em escalada na Guerra dos 12 Dias, diz professor Feliciano de Sá Guimarães analisa que regime iraniano adota escalada lenta, inclusive contra alvos em países árabes do Golfo Pérsico, para aumentar custos para os EUA'], ["Trump rejeita acordo com o Irã, que diz ter fôlego para mais seis meses de 'guerra intensa' Presidente dos EUA levantou a hipótese de que a guerra só deve terminar com a erradicação do exército e das lideranças políticas em Teerã"], ['Mulheres do Irã enfrentam restrições ampliadas pela guerra Direitos das mulheres no regime teocrático no Irã enfrenta problemas estruturais, que se agravam em cenários de guerra, como o atual'], ['Com efeitos globais, guerra contra o Irã mergulha os EUA em um gasto de R$ 4,6 bilhões por dia; veja os números do conflito Conflito, que já atingiu 12 países, expõe objetivos distintos dos principais envolvidos. Escalada regional já deslocou 453 mil pessoas'], ['Trump diz que só "motivo muito bom" justificaria tropas em solo no Irã Parte da justificativa do governo dos EUA para a guerra era impedir que Teerã btivesse uma arma nuclear'], ['Ataque a escola de meninas no Irã expõe horrores da guerra Estados Unidos e Israel não reconheceram ainda a autoria do ataque; ONU pede apuração rápida e imparcial'], ['Programa Brasil no Mundo debate guerra do Irã neste domingo Jornalistas Cristina Serra, Jamil Chade e Yan Boechat analisam os últimos desdobramentos da guerra com a professora da Universidade Federal do Rio de Janeiro Beatriz Bissio.'], ['Como Guerra do Irã coloca em xeque as ambições da China China ainda não sente impacto direto da guerra no Oriente Médio. Mas já calcula o que ela pode significar a longo prazo, não apenas para seus investimentos na região, mas para suas ambições globais.'], ['Hezbollah realiza maior ataque contra Israel desde que entrou na guerra ao lado do Irã O número de mortos já supera 300, além de cerca de 800 feridos, segundo o Ministério da Saúde libanês. A estimativa mais recente calcula 454 mil desalojados, dos quais 110 mil se encontram em abrigos governamentais.'], ['Guerra no Oriente Médio entra no 9º dia; veja tudo o que se sabe Com novos ataques a instalações de armazenamento de petróleo do Irã, conflito entra em nova fase'], ['Irã desafia a máquina de guerra dos EUA no Oriente Médio O que surpreende não é apenas a intensidade das operações iranianas, mas a escala e a coordenação com que vêm sendo conduzidas'], ['Irã se diz preparado para guerra "em grande escala e prolongada" Em pronunciamento, porta-voz da Guarda Revolucionária Islâmica afirma que “os EUA são o principal inimigo nesta guerra”'], ['China é imparcial e objetiva, diz chanceler sobre guerra no Irã Ministro das Relações Exteriores chinês afirmou que o Irã deve ter sua soberania respeitada e volta a pedir um cessar-fogo. Leia no Poder360.'], ['Guerra no Oriente Médio pode impactar eleição brasileira de 2026 Alta do petróleo após conflito envolvendo Irã pressiona inflação e pode afetar cenário político a sete meses da disputa presidencial'], ['Guerra no Oriente Médio: a sucessão no Irã após a morte de Ali Khamenei Especialistas discutem futuro político do país em meio a ataques de Israel e EUA, com filho do líder supremo como possível sucessor'], ['Guerra no Irã completa uma semana: o que aconteceu até agora Presidente do Irã pede desculpas por ataques a países vizinhos, Trump diz que o pedido foi uma rendição, e "aniquila", segundo ministro dos Exteriores iraniano, a chance do arrefecimento do conflito.'], ['Trump diz que não há prazo para fim da guerra com Irã Presidente norte-americano descarta negociação com Teerã e afirma que confronto continuará "custe o que custar"'], ['Trump descarta ajuda das forças curdas na guerra contra o Irã "Somos muito amigos dos curdos, mas não queremos tornar a guerra mais complexa do que já", afirmou o presidente dos Estados Unidos'], ['Zelensky oferece ajuda para combater drones iranianos em telefonema com príncipe saudita Zelensky oferece ajuda para combater drones iranianos em telefonema com príncipe saudita -'], ['Quem ganha e quem perde no Brasil com a guerra no Irã Seu bolso: entenda como a guerra no Irã afeta o preço do petróleo, a inflação, o agronegócio na Gazeta do Povo!'], ['O complexo jogo de perde e ganha provocado pela guerra no Irã Degradação militar, fornecimento de petróleo e mudanças na economia são fatores presentes nos lados da balança do conflito'], ['Sem voo por conta da guerra, Miá Mello cogita sair do Catar por terra e aguarda visto da Arábia Saudita: \'Expert no trajeto\' Atriz ficou "presa" em Doha por conta dos conflitos entre Estados Unidos e Irã'], ['Preço do petróleo dispara após guerra no Irã e fechamento do Estreito de Ormuz Guerra no Irã eleva preço do petróleo em quase 30% na semana após fechamento do Estreito de Ormuz, rota estratégica para exportação global.'], ['SP: aeroporto internacional tem 57 voos cancelados desde o início da guerra Número de viagens para a região foi afetado desde 28 de fevereiro por ataques dos EUA e Israel ao Irã'], ['Turquia alerta para tentativas de promover guerra civil no Irã'], ['Guerra no Oriente Médio ameaça mercados globais de energia Conflito no Irã pode provocar semanas ou meses de alta nos preços dos combustíveis'], ['Guerra contra Irã ameaça atingir de forma prolongada os mercados globais de energia Encontre orientações e notícias sobre economia: investimentos, finanças, negócios, carreira, cotações de Bolsas, moedas, índices econômicos e mais...'], ['Voos para o Oriente Médio começam a ser parcialmente retomados no Aeroporto Internacional de SP, em Guarulhos Desde o início da guerra no Irã, 57 voos foram cancelados no aeroporto; Qatar Airways mantém viagens para Doha suspensas.'], ['Guerra no Irã: petróleo sobe quase 30% na semana por conflito no Oriente Médio Guerra no Irã: petróleo sobe quase 30% na semana por conflito no Oriente Médio - Jornal O Sul'], ['Viagem de Lula aos EUA está suspensa devido à guerra no Irã, diz ministro Ministro Carlos Fávaro afirma que conflito levou à suspensão da agenda internacional prevista para março'], ['Irã pede desculpas a países vizinhos e lança mísseis em Jerusalém; Israel ataca Teerã e Beirute A guerra de Israel e Estados Unidos contra o Irã entrou no oitavo dia neste sábado (7) marcada por uma nova fase da ofensiva israelense contra Teerã e tamb...'], ['Mísseis e drones de baixo custo: as novas armas na guerra no Oriente Médio Como em todos os conflitos, a guerra que opõe o Irã aos Estados Unidos e a Israel constitui um campo de testes para o uso em combate de armamentos novos ou at...'], ['Petróleo tem alta de quase 30% após uma semana de guerra no Irã País é um dos principais produtores globais de petróleo e o conflito acabou afetando diretamente a navegação no Golfo Pérsico'], ['Presidente do Irã cessa ataques, pede desculpas a vizinhos e diz que não se renderá aos EUA Presidente do Irã rejeita exigência de rendição feita por Trump e pede diplomacia em meio à escalada da guerra no Oriente Médio.'], ['Ataque a escola de meninas no Irã revela brutalidade da guerra A tragédia expõe os horrores que o conflito no Oriente Médio pode produzir e seus impactos na vida de menina e mulheres nestes países.'], ["Irã promete continuar atacando vizinhos que 'ajudam seus inimigos' Irã promete continuar atacando vizinhos que 'ajudam seus inimigos' -"], ['Guerra no Irã dificulta plano de Lula de visitar Trump Viagem poderia acontecer ainda em março, mas segue sem definição; conflito no Oriente Médio é obstáculo em agenda'], ['Figuras influentes criticam guerra do Irã e expõem divisões na base de Trump Grande parte das críticas tem se concentrado na influência de Israel na decisão de Trump de ir à guerra'], ['Guerra com Irã aumenta risco global de oferta de energia Em uma semana, conflito já levou à suspensão de 20% do fornecimento de petróleo bruto e gás natural'], ['Guerra Agrava Crises no Oriente Médio A guerra entre EUA e Israel contra o Irã intensifica a violência e crises políticas no Oriente Médio, testando relações comunitárias e sistemas de governo.'], ['Ao exigir rendição incondicional, Trump quer transferir responsabilidade pelo fim da guerra ao Irã, dizem analistas No sétimo dia de conflito, Casa Branca tenta ditar os rumos do conflito e do futuro do Irã; ataques se intensificam no norte iraniano, onde forças curdas planejam invasão'], ["Como o novo drone dos EUA 'copiado' do Irã está mudando a guerra O uso do drone LUCAS em ataques contra o Irã reforça como o Pentágono passou a priorizar a produção em massa de armas baratas e descartáveis"], ['Guerra no Irã: domínio militar dos EUA indica estabilidade, diz professor Hoc Em uma semana desde que Estados Unidos e Israel se uniram para bombardear o Irã, inaugurando um novo conflito militar internacional, um cenário de incertezas,'], ['Trump avisa que vai escalar a guerra neste sábado com ataques a novas ‘áreas e grupos’ do Irã A promessa de escalada do conflito no Oriente Médio veio pouco depois do primeiro sinal de recuo do lado iraniano'], ['F1 abre temporada sob impacto da guerra no Irã e risco de cancelamento A guerra no Irã deve alterar o calendário da F1, que abre sua temporada 2026 neste fim de semana, com a etapa disputada em Melbourne, na Austrália.'], ['Trump diz que vai escalar a guerra neste sábado com ataques a novas ‘áreas e grupos’ do Irã Trump diz que vai escalar a guerra neste sábado com ataques a novas ‘áreas e grupos’ do Irã'], ["Novos ataques em Israel, Irã, Líbano e monarquias do Golfo marcam 8º dia de guerra Trump alerta que Irã será 'duramente atingido' neste sábado; presidente iraniano rejeita rendição e pede desculpas por ataques em território de aliados"], ["Guerra: 'Irã será atingido com muita força', afirma Trump Leia mais sobre a declaração de Trump ameaçando atacar o Irã com força total."], ['Irã afirma que não se renderá aos Estados Unidos e a Israel O Irã prometeu neste sábado (7) que não se renderá aos Estados Unidos nem a Israel, no oitavo dia de guerra, quando caças israelenses bombardearam um dos d...'], ['Guerra no Irã desestabiliza internamente países do Oriente Médio'], ['Irã confirma filho de Khamenei como novo líder; Trump ameaça eliminá-lo Irã confirma filho de Khamenei como novo líder; Trump ameaça eliminá-lo -'], ['Ataques miram depósitos de combustível em Teerã Ataques miram depósitos de combustível em Teerã -'], ['Análise: Guerra com Irã testa resiliência de mundo abalado por tarifas Sinais de tensão marcam presença de aumento de preço de fertilizantes até a exportação de insumos'], ['Guerra no Irã: ministros do G7 fazem reunião de emergência sobre petróleo; as notícias mais recentes Preços de energia dispararam e bolsas caíram em todo o mundo; no Irã, um novo Líder Supremo foi anunciado.'], ['Guerra com Irã expõe vulnerabilidade do país em refino e fertilizantes Especialistas ouvidos pela reportagem apontam quatro caminhos que Brasil precisa avançar para melhorar condições de refino de combustíveis e produção de fertilizantes'], ['Guerra de EUA e Israel contra o Irã amplia número de mortos no Oriente Médio Ataques e contra-ataques envolvendo mísseis e drones atingem vários países da região e deixam milhares de vítimas, segundo balanços atualizados'], ['Principais autoridades iranianas juram lealdade a novo Líder Supremo Mojtaba Khamenei A confirmação de Mojtaba Khamenei como líder supremo ocorre em meio à guerra dos EUA e Israel contra o Irã'], ['Guerra faz preço do diesel subir até 80 centavos em distribuidoras Parte importante do território nacional já convive com aumentos no preço de derivados do petróleo. Motivo é conflito bélico no Irã'], ['Guerra contra Irã pode pressionar inflação global, alerta diretora-geral do FMI Kristalina Georgieva afirma que alta de 10% no petróleo poderia elevar inflação mundial e destaca riscos à segurança energética em meio à guerra'], ['Guerra dos EUA e Israel contra o Irã provoca disparada do preço do petróleo para quase US$ 120 Guerra no Golfo, fechamento do estreito de Hormuz e cortes de produção elevam preço do barril ao maior nível desde 2020'], ['Trump diz que decidirá, com Netanyahu, quando guerra com Irã acabará'], ['Vídeo: Israel visa economia do Irã com ataques à infraestrutura petrolífera; Trump cogita envio de tropas para confiscar urânio Ataques mergulharam a capital iraniana em uma escuridão apocalíptica com forte cheiro de queimado e lembraram as cenas dos campos de petróleo do Kuwait em chamas durante a Guerra do Golfo de 1991'], ['Qual motivo da guerra entre EUA e Irã? 4 objetivos listados por Trump'], ['Dólar se valoriza com a busca por ativos seguros e petróleo sobe com guerra no Irã Alta dos preços do petróleo alimentou temores inflacionários em todo o mundo'], ['China celebra ano ‘histórico’ na relação com EUA, apesar da guerra com Irã Pequim também está vulnerável à crescente instabilidade no Oriente Médio'], ['Quem é Mojtaba Khamenei, escolhido para ser o novo líder supremo do Irã Mojtaba Khamenei, de 56 anos, foi nomeado pela Assembleia de Especialistas como o novo líder supremo do Irã, sucedendo seu pai, Ali Khamenei, morto em um ataque aéreo há pouco mais de uma semana.', 'líder supremo do Irã, sucedendo seu pai, Ali Khamenei, morto em um ataque aéreo há pouco mais de uma semana. Figura de linha dura com forte influência

In [83]:
# Parte dos Embeddings

model_emb = SentenceTransformer("all-MiniLM-L6-v2")

sentences = df_final["text"].tolist()
embeddings = model_emb.encode(sentences)

df_final["embedding"] = list(embeddings)
df_final.head()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,title,description,content,url,publishedAt,source,text,embedding
0,Irã afirma ter atingido petroleiro americano n...,"A Guarda Revolucionária afirmou, em comunicado...",A Guarda Revolucionária do Irã afirmou nesta q...,https://valor.globo.com/mundo/noticia/2026/03/...,2026-03-05T11:04:52Z,Valor Econômico,Irã afirma ter atingido petroleiro americano n...,"[0.06447954, 0.077835895, -0.097416736, 0.0236..."
1,Países do Golfo estão preocupados com risco de...,O temor é que uma crise se instale durante a e...,"""Quando conversamos com os países da região, e...",https://valor.globo.com/mundo/noticia/2026/03/...,2026-03-05T11:01:33Z,Valor Econômico,Países do Golfo estão preocupados com risco de...,"[0.038895156, 0.087890096, -0.07263952, -0.036..."
2,Guerra de Trump no Irã leva gasolina a seu mai...,Alta recente está ligada à guerra envolvendo o...,247 - Os preços da gasolina nos Estados Unidos...,https://www.brasil247.com/economia/guerra-de-t...,2026-03-05T11:00:03Z,Brasil 247,Guerra de Trump no Irã leva gasolina a seu mai...,"[0.040432967, 0.042618096, -0.04323365, -0.041..."
3,Sri Lanka tenta salvar vidas em outro navio do...,Torpedo americano afundou embarcação de guerra...,O governo do Sri Lanka afirmou nesta quinta-fe...,https://www1.folha.uol.com.br/mundo/2026/03/sr...,2026-03-05T10:49:00Z,Folha de S.Paulo,Sri Lanka tenta salvar vidas em outro navio do...,"[0.015832234, 0.092888854, -0.11163524, -0.022..."
4,"Pesquisa eleitoral, dados de emprego e avanço ...",Cesta Básica: tudo que você precisa saber para...,A quinta-feira (5) começa com o mercado de olh...,https://valorinveste.globo.com/mercados/renda-...,2026-03-05T10:44:19Z,Valor Investe,"Pesquisa eleitoral, dados de emprego e avanço ...","[0.0436363, 0.08206621, -0.060586512, -0.02586..."

In [84]:
# Parte da busca vetorial 
def retrieve(query: str, top_k: int = 3) -> pd.DataFrame:
    query_emb = model_emb.encode([query])
    matrix = np.vstack(df_final["embedding"].values)

    sims = cosine_similarity(query_emb, matrix)[0]
    top_idx = np.argsort(sims)[::-1][:top_k]

    results = df_final.iloc[top_idx].copy()
    results["score"] = sims[top_idx]
    return results

query = "Quao impactante será o fechamendo to estreito de Ormuz"
retrieve(query, top_k=3)

,title,description,content,url,publishedAt,source,text,embedding,score
114,Quem fechou o Estreito de Ormuz: o Irã ou as s...,Ninguém em sã consciência arriscaria ordenar q...,Outro dia escutei num evento do mercado segura...,https://www.estadao.com.br/economia/antonio-pe...,2026-03-08T20:00:00Z,"O Estado de S. Paulo,",Quem fechou o Estreito de Ormuz: o Irã ou as s...,"[0.013994815, 0.08227263, -0.07365464, 0.01039...",0.651695
21,Guerra no Irã: bloqueio do Estreito de Ormuz p...,"Frango, madeira e papel estão entre os itens q...","Segundo a consultoria MTM Logix, especializada...",https://extra.globo.com/economia/noticia/2026/...,2026-03-05T10:13:47Z,EXTRA,Guerra no Irã: bloqueio do Estreito de Ormuz p...,"[0.06743132, 0.05825529, -0.0595583, -0.007420...",0.558202
52,Preço do petróleo dispara após guerra no Irã e...,Guerra no Irã eleva preço do petróleo em quase...,O preço do petróleo registrou forte alta nos m...,https://www.diariodocentrodomundo.com.br/preco...,2026-03-07T18:12:31Z,Diário do Centro do Mundo,Preço do petróleo dispara após guerra no Irã e...,"[0.043904163, 0.054304473, -0.03347153, -0.004...",0.516601

In [85]:
def build_context(query: str, top_k: int = 3) -> str:
    retrieved = retrieve(query, top_k)
    context = "\n\n".join(retrieved["text"].tolist())
    return context

query = "Quao impactante será o fechamendo to estreito de Ormuz"
context = build_context(query, top_k=5)
print(context)

Quem fechou o Estreito de Ormuz: o Irã ou as seguradoras? Ninguém em sã consciência arriscaria ordenar que um navio que custa milhões de dólares, transportando uma carga que vale outros tantos milhões, fizesse essa travessia sob guerra

Guerra no Irã: bloqueio do Estreito de Ormuz pode afetar exportações brasileiras Frango, madeira e papel estão entre os itens que cruzam a rota. No ano passado, 158.300 contêineres saíram do país rumo ao Golfo Pérsico

Preço do petróleo dispara após guerra no Irã e fechamento do Estreito de Ormuz Guerra no Irã eleva preço do petróleo em quase 30% na semana após fechamento do Estreito de Ormuz, rota estratégica para exportação global.

Guerra no Oriente Médio pode impactar eleição brasileira de 2026 Alta do petróleo após conflito envolvendo Irã pressiona inflação e pode afetar cenário político a sete meses da disputa presidencial

Irã afirma que atacou petroleiro dos EUA no Golfo Pérsico Guerra entrou no sexto dia

In [ ]:
# Download do modelo pra usar
# O GEMMA demanda um login pra uso, e também esta hard-coded    
#model_name = "distilgpt2"
from huggingface_hub import login

login("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")
model_name = "google/gemma-3-270m"  

tokenizer = AutoTokenizer.from_pretrained(model_name)
model_gen = AutoModelForCausalLM.from_pretrained(model_name)

#if tokenizer.pad_token is None:
#    tokenizer.pad_token = tokenizer.eos_token

config.json: 0.00B [00:00, ?B/s]

C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dell\.cache\huggingface\hub\models--google--gemma-3-270m. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

In [105]:
def rag_answer(query: str, top_k: int = 5, max_tokens: int = 150) -> str:
    
    context = build_context(query, top_k)

    prompt = f"""Responda à pergunta usando apenas o contexto abaixo.

Contexto:
{context}

Pergunta:
{query}

Resposta:
"""

    inputs = tokenizer(prompt, return_tensors="pt", padding=True, truncation=True)

    with torch.no_grad():
        outputs = model_gen.generate(
            **inputs,
            no_repeat_ngram_size=3,
            max_new_tokens=max_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    prompt_length = inputs["input_ids"].shape[1]

    generated_tokens = outputs[0][prompt_length:]

    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    only_model_answer =  answer.split(".")
    return only_model_answer[0]
rag_answer("Qual a area econômica no Brasil mais afetada com a guerra?", top_k=5)

# Algumas coisas que eu notei que provavelmente são contadas com minha falta de capacidade mesmo

# 1 -> O modelo atualmente tem dificuldade em responder perguntas que demandam respostas precisas sobre os eventos
# como por exemplo, o nome do estreito que foi fechado por conta do conflito (Estreito de Ormuz), porém, responde até que
# adequadamente algumas perguntas , como o caso de: "Quais paises estão participando da guerra diretamente?", talvez pela falta
# de informação, ele não consiga identificar Israel ou outros exemplos, mas ele responde que é os Estados Unidos e o Irâ, o que
# não está incorreto, mas não é a resposta total

# 2 -> Já em algumas perguntas mais genéricas, ele tem uma tendência de dar uma resposta bem insatisfatória, como a seguinte:
# "Como o conflito no Oriente Médio afeta o Brasil", a resposta sai bem genérica

# 3 -> Ele é meio incapaz de responder sobre temas diversos sem a inserção da palavra direta desse tema no assunto, por exemplo
# com a pergunta "Quais os impactos do fechamento do Estreito de Ormuz", ele dá uma resposta bem genérica, caso a palavra "economica"
# por exemplo não seja inserida na query

'A economia brasileira sofre com a crise da guerra no Oriente Medio, que afetará o mercado de petróleo e a inflacao'